inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/EndOfLine:
  Enabled: false

StringLiterals:
  Enabled: false

BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Rails/InverseOf:
  Enabled: false