require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reference_tables/sectors", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ReferenceTables::Sector. As you add validations to ReferenceTables::Sector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:reference_tables_sector)
  end

  let(:invalid_attributes) do
    attributes_for(:reference_tables_sector_invalid)
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ReferenceTables::SectorsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe "GET /index" do
    it "renders a successful response" do
      ReferenceTables::Sector.create! valid_attributes
      get reference_tables_sectors_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sector = ReferenceTables::Sector.create! valid_attributes
      get reference_tables_sector_url(sector), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReferenceTables::Sector" do
        expect {
          post reference_tables_sectors_url,
               params: { reference_tables_sector: valid_attributes }, headers: valid_headers, as: :json
        }.to change(ReferenceTables::Sector, :count).by(1)
      end

      it "renders a JSON response with the new reference_tables_sector" do
        post reference_tables_sectors_url,
             params: { reference_tables_sector: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReferenceTables::Sector" do
        expect {
          post reference_tables_sectors_url,
               params: { reference_tables_sector: invalid_attributes }, as: :json
        }.to change(ReferenceTables::Sector, :count).by(0)
      end

      it "renders a JSON response with errors for the new reference_tables_sector" do
        post reference_tables_sectors_url,
             params: { reference_tables_sector: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        attributes_for(:reference_tables_sector)
      end

      it "updates the requested reference_tables_sector" do
        sector = ReferenceTables::Sector.create! valid_attributes
        patch reference_tables_sector_url(sector),
              params: { reference_tables_sector: new_attributes }, headers: valid_headers, as: :json
        sector.reload
      end

      it "renders a JSON response with the reference_tables_sector" do
        sector = ReferenceTables::Sector.create! valid_attributes
        patch reference_tables_sector_url(sector),
              params: { reference_tables_sector: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the reference_tables_sector" do
        sector = ReferenceTables::Sector.create! valid_attributes
        patch reference_tables_sector_url(sector),
              params: { reference_tables_sector: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reference_tables_sector" do
      sector = ReferenceTables::Sector.create! valid_attributes
      expect {
        delete reference_tables_sector_url(sector), headers: valid_headers, as: :json
      }.to change(ReferenceTables::Sector, :count).by(-1)
    end
  end
end
