# Put this in the file: .github/workflows/verify.yml

name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: costek
          POSTGRES_DB: rptconsultants_backend_v2_test
          POSTGRES_PASSWORD: costek
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: costek
        run: |
          bundle exec rails db:setup && bundle exec rake db:test:prepare



      - name: Run tests
        run: bundle exec rspec
